PRAGMA foreign_keys=ON;

BEGIN TRANSACTION;

CREATE TABLE FOLDERS 
(
IdFolder INTEGER CONSTRAINT PK_FOLDERS PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT NOT NULL ON CONFLICT ROLLBACK, 
IdParent INTEGER NOT NULL ON CONFLICT ROLLBACK CONSTRAINT FK_FOLDERS REFERENCES FOLDERS (IdFolder) 
ON DELETE RESTRICT ON UPDATE CASCADE, NameFolder TEXT (255) NOT NULL
);

INSERT INTO FOLDERS VALUES(0,0,'Application root folder');
INSERT INTO FOLDERS VALUES(1,0,'Local database');

CREATE TABLE TYPES (IdType INTEGER PRIMARY KEY NOT NULL, NameType TEXT (255) NOT NULL, Note TEXT (4000));

INSERT INTO TYPES VALUES(0,'unknown',NULL);
INSERT INTO TYPES VALUES(1,'boolean',NULL);
INSERT INTO TYPES VALUES(2,'datetime',NULL);
INSERT INTO TYPES VALUES(3,'integer',NULL);
INSERT INTO TYPES VALUES(4,'text','');
INSERT INTO TYPES VALUES(5,'password',NULL);
INSERT INTO TYPES VALUES(6,'folder name',NULL);
INSERT INTO TYPES VALUES(7,'file name',NULL);

CREATE TABLE SETTINGS 
(
IdFolder INTEGER NOT NULL, 
IdSetting TEXT NOT NULL, IdType INTEGER NOT NULL, 
SettingValue TEXT, 
Rank INTEGER NOT NULL, 
CONSTRAINT PK_SETTINGS PRIMARY KEY (IdFolder, IdSetting) 
ON CONFLICT ROLLBACK, CONSTRAINT FK_SETTINGS_FOLDERS FOREIGN KEY (IdFolder) 
REFERENCES FOLDERS (IdFolder) ON DELETE RESTRICT ON UPDATE CASCADE, 
CONSTRAINT FK_SETTINGS_TYPES FOREIGN KEY (IdType) REFERENCES TYPES (IdType) 
ON DELETE RESTRICT ON UPDATE CASCADE
);

DELETE FROM sqlite_sequence;

INSERT INTO sqlite_sequence VALUES('FOLDERS',2);

CREATE UNIQUE INDEX UX_NameFolder ON FOLDERS (IdParent, NameFolder);

CREATE VIEW V_SETTINGS AS
    SELECT A.IdFolder,
           A.IdSetting,
           A.IdType,
           B.NameType,
           A.SettingValue,
           A.Rank,
           CASE WHEN A.IdType = 1 THEN A.SettingValue ELSE "" END AS BooleanValue
      FROM SETTINGS A
      LEFT JOIN TYPES B
      ON A.IdType=B.IdType
      ORDER BY A.Rank, A.IdSetting;
COMMIT;
